/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/shop` | `/shop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/social` | `/social`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/social/settings` | `/social/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/cart` | `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/menu` | `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/shop` | `/shop`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/social` | `/social`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/social/settings` | `/social/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/cart${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/menu${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/shop${`?${string}` | `#${string}` | ''}` | `/shop${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/social${`?${string}` | `#${string}` | ''}` | `/social${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/social/settings${`?${string}` | `#${string}` | ''}` | `/social/settings${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/shop` | `/shop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/social` | `/social`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/social/settings` | `/social/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; };
    }
  }
}
