export const STRIPE_PUBLISHABLE_KEY = process.env.EXPO_PUBLIC_STRIPE_KEY?.trim() ?? '';

export const CARD_PAYMENTS_ENABLED = process.env.EXPO_PUBLIC_ENABLE_CARD_PAYMENTS === 'true';

export const STRIPE_IS_CONFIGURED = CARD_PAYMENTS_ENABLED && STRIPE_PUBLISHABLE_KEY.length > 0;
