CREATE TABLE IF NOT EXISTS `social_gift_orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `folio` VARCHAR(40) DEFAULT NULL,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `mesa_id` INT UNSIGNED NOT NULL,
  `gift_product_id` INT UNSIGNED NOT NULL,
  `sender_user_id` INT UNSIGNED NOT NULL,
  `recipient_user_id` INT UNSIGNED NOT NULL,
  `sender_nombre` VARCHAR(150) NOT NULL,
  `recipient_nombre` VARCHAR(150) NOT NULL,
  `sender_mesa` VARCHAR(50) DEFAULT NULL,
  `recipient_mesa` VARCHAR(50) DEFAULT NULL,
  `gift_nombre` VARCHAR(150) NOT NULL,
  `gift_descripcion` VARCHAR(255) DEFAULT NULL,
  `gift_precio` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `gift_imagen` VARCHAR(255) DEFAULT NULL,
  `status` ENUM('listo','reclamado','entregado','cancelado') NOT NULL DEFAULT 'listo',
  `reclamado_por` INT UNSIGNED DEFAULT NULL,
  `reclamado_at` DATETIME DEFAULT NULL,
  `entregado_por` INT UNSIGNED DEFAULT NULL,
  `entregado_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sgo_rest_status` (`restaurante_id`, `status`),
  KEY `idx_sgo_mesa_status` (`mesa_id`, `status`),
  KEY `idx_sgo_sender` (`sender_user_id`),
  KEY `idx_sgo_recipient` (`recipient_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
